name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy latest version
        run: |
          set -e

          cd /home/ubuntu/Trajectory

          echo "Fetching latest code..."
          git fetch origin

          echo "Resetting to latest commit..."
          git reset --hard origin/main

          echo "Building and starting containers..."
          docker compose \
              -f docker-compose.yml \
              -f docker-compose.prod.yml \
              up --build -d

          echo "Cleaning unused images..."
          docker image prune -f

          echo "Deployment completed successfully!"